"""empty message

Revision ID: c6e770b497b7
Revises: a47e085ab4ef
Create Date: 2021-10-27 22:58:18.378086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e770b497b7'
down_revision = 'a47e085ab4ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('about', 'title',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('about', 'text',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('about', 'text',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('about', 'title',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
